Imprint Creation
lukaswelte/websocket-map pull request #60
Opened 2016-11-12 17:47 UTC by AdrianBor

I’ve a quick issue with the link from ProfilDetail.js… I can’t make the link… I really don’t know why…. Could you fix it ?

2016-11-12 17:54 UTC, lukaswelte requested changes

2016-11-12 17:54 UTC, lukaswelte commented on src/pages/ProfilDetail.js
> +    ShowImprint: bindActionCreators(goToImprint, dispatch),
this s of `ShowImprint` needs to be lower case so `showImprint`

2016-11-12 17:54 UTC, lukaswelte commented on src/pages/ImprintDetail.css
> +.ImprintDetail-card{
You need to clean the css to just have the classes needed for the page

2016-11-12 17:55 UTC, AdrianBor commented on src/pages/ImprintDetail.css
> +.ImprintDetail-card{
ok!

2016-11-12 17:55 UTC, AdrianBor commented on src/pages/ProfilDetail.js
> +    ShowImprint: bindActionCreators(goToImprint, dispatch),
ok :)

2016-11-12 18:03 UTC, AdrianBor commented
@lukaswelte Changements are done.

2016-11-12 18:05 UTC, lukaswelte commented
That is great. Can we have this button also on login and introduction @AdrianBor?

2016-11-12 18:06 UTC, lukaswelte approved these changes

2016-11-12 18:27 UTC, AdrianBor commented
ok @lukaswelte I'm done, I just have an issue with the styling on the introduction page. I'm trying to do that but doesn't work...

<LegalButton onClick={showImprint} style={{color:'#252525'}}/>

could you tell me what's missing ?

2016-11-12 18:28 UTC, lukaswelte commented
To be able to tell you what is missing i need to know what your problem is ;) 

Maybe just that the text is white on a white background?

2016-11-12 18:29 UTC, AdrianBor commented
Totally right. The text is white on white and for this specific case i try to change the color to black directly on the page.

2016-11-12 18:39 UTC, lukaswelte commented on src/components/LegalButton.js
> +    const { onClick } = this.props;
pass a property color in here.
Then apply an inline style that sets the color. Thereby you can pass the desired color into the component

2016-11-12 18:54 UTC, AdrianBor commented
Ok @lukaswelte I've to go right now, I tried to do it but I've still the problem. I don't know where to Call the color style. I guess I'm very close but...

Sorry for behing so bad! Soon no more code for us maybe! 💃 💃 💃

2016-11-13 11:31 UTC, AdrianBor commented
ok @lukaswelte , done! thanks a lot.

2016-11-13 11:44 UTC, merged