WIP Profile page
lukaswelte/websocket-map pull request #76
Opened 2016-11-15 20:22 UTC by AdrianBor

2016-11-16 14:02 UTC, AdrianBor commented
![](https://github.trello.services/images/mini-trello-icon.png) [Profile Page](https://trello.com/c/pQYLeHS2/113-profile-page)

2016-11-16 14:04 UTC, AdrianBor commented
Friend section have been added BUT will be removed/post pone based on the difficulty to make it happend.

2016-11-18 14:49 UTC, AdrianBor commented
Hi @lukaswelte , You can check my branch. You can hide the friend part. 
The first ME, I & Munich is when there is nothing so remove all the rest except contact.
When we start saving marks AND we are in the city, the trip list appear.

Just let me know if it'S not clear to telling you in a better way :)

2016-11-18 15:14 UTC, lukaswelte commented
So this is ready to merge from your side now? If so please remove the WIP in the title.

2016-11-18 15:48 UTC, AdrianBor commented
Yes for me it's done for the moment.

2016-11-18 21:33 UTC, lukaswelte requested changes

2016-11-18 21:33 UTC, lukaswelte commented on src/components/MarkMapMarker.css
> +  -webkit-box-shadow: 0px 0px 0px 4px rgba(255,255,255, 0.3);
you can remove the prefixed versions so -webkit -moz etc. as they are automatically added (less code :)

2016-11-18 21:33 UTC, lukaswelte commented on src/pages/ProfilDetail.css
> +  -webkit-box-shadow: 0px 0px 0px 4px rgba(251, 117, 127, 0.8);
same here

2016-11-19 17:07 UTC, AdrianBor commented
@lukaswelte Modifications done :)

2016-11-19 17:13 UTC, lukaswelte approved these changes

2016-11-19 17:13 UTC, merged